---
title: "Infectious Diseases"
author: "Francis Lin | #TidyTuesday |"
date: "2019-12-10"
output: rmarkdown::github_document
---

# Introduction

This dataset, originally from [Project Tycho](https://www.tycho.pitt.edu/), contains the number of people infected by a number of diseases in each state. Since I heard R could do animations pretty well using gganimate, I wanted to animate how the rate of infection changed for a certain disease over time.

# R Program

## Set up

```{r setup, message=FALSE}
# source utilities
source("../utilities.R")

# packages
library(tidyverse)
library(lubridate)
library(gganimate)

# set data path
data_path <- set_data_path()
```

## Load Data

```{r load data}
# read in data
diseases <- read.csv(paste0(data_path, "diseases.csv"))
```

# Plot

```{r plot}
# plot number of tickets by weekday

disease <- "Smallpox"

data <- diseases %>%
    filter(disease == disease) %>%
    mutate(rate = count / population * 10000 * 52 / weeks_reporting)

p <- ggplot(data) +
    aes(x = state, y = rate) +
    geom_bar(stat = "identity") +
    coord_flip() + 
    transition_time(year) +
    labs(title = "Measles Rate by State, Year: {frame_time}")

animation <- animate(p, fps=5, end_pause=10)
animation
```

# Save Plot

```{r save image}
anim_save("plot/plot_2019-12-10.gif", animation)
```

