---
title: "#TidyTuesday 2020-01-10"
author: "Francis Lin"
output: rmarkdown::github_document
---

Set up

```{r setup, message=FALSE}
# source utilities
source("../utilities.R")

# packages
library(tidyverse)
library(readr)

# set data path
data_path <- set_data_path()
```

Load Data

```{r load data}
# read in data
temperature <- read_csv(paste0(data_path, "temperature.csv"), col_types=cols(date = col_date(format="%Y-%m-%d")))
```

Manipulate Data

```{r manipulate data}
# find average temperature for each day
max_temp_date <- temperature %>%
    filter(temp_type == "max") %>%
    group_by(date) %>% 
    summarise(daily_temp = mean(temperature, na.rm=TRUE))

# find average temperature for each year
max_temp_annual <- max_temp_date %>%
    mutate(year=format(date, "%Y")) %>%
    group_by(year) %>%
    summarise(annual_temp = mean(daily_temp, na.rm=TRUE))

# find difference of each year from average
max_temp_annual$annual_temp_diff <- max_temp_annual$annual_temp - mean(max_temp_annual[which(max_temp_annual$year %in% c(1960, 1961)),]$annual_temp)
```

Plot

```{r plot}
# plot
p <- ggplot(data=max_temp_annual, aes(x=year, y=annual_temp_diff, fill=factor(ifelse(year==2019,"Highlighted","Normal")))) +
    
    # bar graph
    geom_bar(stat="identity", width=0.8) +
    
    # axes and colors
    scale_fill_manual(name = "date", values=c("red","grey"))+
    theme(text = element_text(size=12), panel.background = element_blank(), panel.grid.major = element_blank(), axis.title.y=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), legend.position="none") +
    xlab("Year") + 
    scale_y_continuous(breaks=seq(floor(min(max_temp_annual$annual_temp_diff)), ceiling(max(max_temp_annual$annual_temp_diff)), by=1), labels=function(x) {ifelse(x>=0, paste0("+", x, "°C"), paste0(x, "°C"))}) + 
    ggtitle("Australia's Average Max Temperature by Year") +
    
    # annotation arrow
    annotate("segment", x = 100, xend = 108, y = 4.4, yend = 4.4, colour = "red", size=0.5, alpha=1, arrow=arrow(length = unit(0.1, "inches"))) + 
    
    # annotation text
    annotate("text", x = 5, y = 3, hjust=0, label = "Annual temperature above or below\nthe 1960-1961 average", color="dimgrey") + 
    annotate("text", x=96, y=4.4, label="2019", color="dimgrey") + 
    annotate("text", x=8, y=-1.8, label="1917", color="dimgrey") + 
    
    # horizontal lines
    geom_hline(yintercept=c(-1.5, -1, -0.5, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4), color="white", size=0.5) + 
    geom_hline(yintercept=0, color="black", size=0.5)

p
```

Save Image

```{r save plot}
# save image
ggsave("plot/plot_2020-01-07.png", width = 29, height = 21, units = "cm", dpi = "retina")
```

Session Info

```{r session info}
#session info
sessionInfo()
```

